# Generated by Django 4.2.9 on 2024-01-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('group_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_amount', models.IntegerField()),
            ],
        ),
    ]
