# Generated by Django 3.2.23 on 2024-01-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=60)),
                ('employee_designation', models.CharField(max_length=60)),
                ('employee_salary', models.CharField(max_length=30)),
                ('employee_experiece', models.IntegerField()),
            ],
        ),
    ]
