# Generated by Django 4.2.9 on 2024-01-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_contact', models.CharField(max_length=60)),
                ('number_of_items', models.IntegerField()),
                ('invoice_date', models.DateField()),
            ],
        ),
    ]
